steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -t europe-west3-docker.pkg.dev/cpl-mo/test-docker-registry/prodreactnodecontainer:03 . &&
        echo "✅ Finished Docker build"
        docker push europe-west3-docker.pkg.dev/cpl-mo/test-docker-registry/prodreactnodecontainer:03 &&
        echo "✅ Finished Docker push"
        
