steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        IMAGE_TAG="03"
        echo "[INFO] Finished Docker build"
        echo "[SUCCESS] Finished Docker build"
        echo "[INFO] Finished Docker push"
        echo "[SUCCESS] Finished Docker push"
        
